## 1 Introduction

Welcome back!!  The Jupyter interface should now be feeling familiar, and you should have an intuition for how Python processes cells, the difference between a code cell and a markdown cell, and some basic operations.

In lab today, we're going to work on three concepts: panda dataframes and indexing (these are confusing so we're going to review them and provide stronger guidance on how to think about them), using conditional statements, and writing more complex formulas.

### 1.1 Libraries

Let's begin by importing our libraries. How might you do that on your own?

In [33]:
import numpy as np
import pandas as pd
import math
from datascience import *

pd.options.display.float_format = '{:.2f}'.format

### 1.2 Importing our Data

If you brought one of your .csv datasets, you can upload it now, and work with that dataset throughout this lab.  Otherwise, we will be working with the "geographic" mobility dataset I introduced a few weeks ago.  It includes data on renters versus owners and when they moved into their current house.

If you are working on your own dataset, you'll be replacing my code with your own in every step.

I am going to work with the downloaded raw .csv file from the ACS.  But you can always choose to edit your ACS file first and then bring it into Python.

In [34]:
#specify datatypes so FIPS numbers, etc. read in properly
variable_types = {'Geo.id': 'str', 'GEO.id2': 'str'}
#variable_types in this case is known as a "dictionary" - thanks to the curly brackets
#it tells Python that every time it sees "Geo.id", make that variable a string

#read in my csv file, saying it is comma delimited, I want index row 0 to be the header, 
# I want to skip index row 1 (the long variable names), and I want to assign the datatypes
#I've outlined above.

pd.read_csv('ACS_17_5YR_B07013_with_ann.csv', delimiter = ',', header=[0], skiprows=[1], dtype=variable_types)

,GEO.id,GEO.id2,GEO.display-label,HD01_VD01,HD02_VD01,HD01_VD03,HD02_VD03,HD01_VD04,HD02_VD04,HD01_VD05,...,HD01_VD15,HD02_VD15,HD01_VD16,HD02_VD16,HD01_VD17,HD02_VD17,HD01_VD18,HD02_VD18,HD01_VD19,HD02_VD19
0,0500000US06001,06001,"Alameda County, California",1578306,1317,876019,7381,702287,7464,1378727,...,5375,628,16635,1336,20040,1116,6019,621,14021,996
1,0500000US06013,06013,"Contra Costa County, California",1101965,850,722925,6012,379040,6076,957822,...,5462,718,7339,909,9945,1204,4364,587,5581,1054
2,0500000US06075,06075,"San Francisco County, California",834977,1120,362591,4685,472386,4717,724483,...,2800,432,16557,1088,12395,1228,2634,503,9761,1052
3,0500000US06077,06077,"San Joaquin County, California",699091,1401,386343,6073,312748,5944,596731,...,1894,575,4867,820,3460,678,1921,558,1539,450
4,1400000US06001400100,06001400100,"Census Tract 4001, Alameda County, California",2953,189,2621,228,332,171,2418,...,91,99,67,91,30,31,30,31,0,12
5,1400000US06001400200,06001400200,"Census Tract 4002, Alameda County, California",1889,89,1154,115,735,115,1694,...,0,12,28,27,41,47,31,44,10,11
6,1400000US06001400300,06001400300,"Census Tract 4003, Alameda County, California",5050,303,2708,375,2342,360,4380,...,11,19,131,105,35,41,0,17,35,41
7,1400000US06001400400,06001400400,"Census Tract 4004, Alameda County, California",3820,232,1591,283,2229,344,3296,...,8,15,87,69,9,15,0,12,9,15
8,1400000US06001400500,06001400500,"Census Tract 4005, Alameda County, California",3864,308,1474,277,2390,341,3000,...,8,12,161,105,36,36,0,12,36,36
9,1400000US06001400600,06001400600,"Census Tract 4006, Alameda County, California",1580,174,886,187,694,140,1200,...,17,20,93,88,0,12,0,12,0,12
10,1400000US06001400700,06001400700,"Census Tract 4007, Alameda County, California",4753,487,1982,407,2771,509,4016,...,25,32,142,71,34,45,0,12,34,45
11,1400000US06001400800,06001400800,"Census Tract 4008, Alameda County, California",3665,363,1150,325,2515,505,3058,...,0,12,99,87,43,48,0,12,43,48
12,1400000US06001400900,06001400900,"Census Tract 4009, Alameda County, California",2377,189,814,171,1563,227,2097,...,0,12,56,53,0,12,0,12,0,12
13,1400000US06001401000,06001401000,"Census Tract 4010, Alameda County, California",6210,474,2127,525,4083,606,5438,...,0,17,117,112,20,31,0,17,20,31
14,1400000US06001401100,06001401100,"Census Tract 4011, Alameda County, California",4072,315,1039,282,3033,402,2999,...,42,58,178,171,27,44,0,12,27,44
15,1400000US06001401200,06001401200,"Census Tract 4012, Alameda County, California",2580,186,1143,209,1437,221,2140,...,0,12,57,69,0,12,0,12,0,12
16,1400000US06001401300,06001401300,"Census Tract 4013, Alameda County, California",3344,583,654,208,2690,568,2380,...,28,32,113,60,45,49,25,38,20,28
17,1400000US06001401400,06001401400,"Census Tract 4014, Alameda County, California",3725,415,635,274,3090,407,3188,...,0,12,26,29,31,36,0,12,31,36
18,1400000US06001401500,06001401500,"Census Tract 4015, Alameda County, California",2618,294,970,223,1648,278,1958,...,0,12,7,10,26,26,6,9,20,24
19,1400000US06001401600,06001401600,"Census Tract 4016, Alameda County, California",2016,197,483,146,1533,226,1630,...,6,9,5,8,23,28,0,12,23,28
20,1400000US06001401700,06001401700,"Census Tract 4017, Alameda County, California",2653,353,1312,301,1341,352,2299,...,0,12,10,15,0,12,0,12,0,12
21,1400000US06001401800,06001401800,"Census Tract 4018, Alameda County, California",1916,269,373,121,1543,268,1461,...,0,12,93,85,7,12,0,12,7,12
22,1400000US06001402200,06001402200,"Census Tract 4022, Alameda County, California",2512,192,876,190,1636,236,2158,...,0,12,35,27,21,24,9,13,12,20
23,1400000US06001402400,06001402400,"Census Tract 4024, Alameda County, California",2772,315,750,220,2022,261,2489,...,31,31,0,12,0,12,0,12,0,12
24,1400000US06001402500,06001402500,"Census Tract 4025, Alameda County, California",1737,184,250,140,1487,187,1601,...,0,12,0,12,0,12,0,12,0,12
25,1400000US06001402600,06001402600,"Census Tract 4026, Alameda County, California",1236,92,169,63,1067,95,1036,...,0,12,33,51,68,62,0,12,68,62
26,1400000US06001402700,06001402700,"Census Tract 4027, Alameda County, California",1805,206,429,139,1376,214,1251,...,8,11,33,26,0,12,0,12,0,12
27,1400000US06001402800,06001402800,"Census Tract 4028, Alameda County, California",3900,270,289,129,3611,266,2491,...,0,12,127,110,26,31,0,12,26,31
28,1400000US06001402900,06001402900,"Census Tract 4029, Alameda County, California",1294,94,21,30,1273,89,1092,...,0,12,42,29,12,17,0,12,12,17
29,1400000US06001403000,06001403000,"Census Tract 4030, Alameda County, California",3148,235,804,245,2344,265,2748,...,0,12,0,12,151,99,26,41,125,105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
879,1400000US06077005119,06077005119,"Census Tract 51.19, San Joaquin County, Califo...",8047,432,5059,646,2988,827,6684,...,0,17,67,91,271,221,80,100,191,207
880,1400000US06077005122,06077005122,"Census Tract 51.22, San Joaquin County, Califo...",6305,507,4504,660,1801,472,5311,...,0,17,32,51,0,17,0,17,0,17
881,1400000US06077005123,06077005123,"Census Tract 51.23, San Joaquin County, Califo...",4552,333,2827,371,1725,388,3819,...,0,12,26,42,13,20,0,12,13,20
882,1400000US06077005124,06077005124,"Census Tract 51.24, San Joaquin County, Califo...",3201,288,1532,282,1669,312,2531,...,0,12,28,33,37,57,0,12,37,57
883,1400000US06077005125,06077005125,"Census Tract 51.25, San Joaquin County, Califo...",1879,122,1038,241,841,221,1697,...,8,12,0,12,8,12,8,12,0,12
884,1400000US06077005126,06077005126,"Census Tract 51.26, San Joaquin County, Califo...",3961,378,1918,392,2043,457,3349,...,10,17,0,12,86,99,0,12,86,99
885,1400000US06077005127,06077005127,"Census Tract 51.27, San Joaquin County, Califo...",5926,312,4387,444,1539,454,5186,...,0,17,0,17,97,55,81,54,16,19
886,1400000US06077005129,06077005129,"Census Tract 51.29, San Joaquin County, Califo...",3497,279,2510,366,987,390,3166,...,10,15,0,12,0,12,0,12,0,12
887,1400000US06077005130,06077005130,"Census Tract 51.30, San Joaquin County, Califo...",3389,300,2017,353,1372,342,2772,...,0,12,0,12,19,28,6,10,13,21
888,1400000US06077005131,06077005131,"Census Tract 51.31, San Joaquin County, Califo...",4344,601,2554,452,1790,601,3973,...,0,17,0,17,6,12,6,12,0,17
889,1400000US06077005132,06077005132,"Census Tract 51.32, San Joaquin County, Califo...",3112,332,1530,340,1582,424,2343,...,0,12,89,104,23,41,0,12,23,41
890,1400000US06077005133,06077005133,"Census Tract 51.33, San Joaquin County, Califo...",3859,359,2110,420,1749,492,3144,...,0,12,62,94,14,21,14,21,0,12
891,1400000US06077005134,06077005134,"Census Tract 51.34, San Joaquin County, Califo...",5024,261,2694,437,2330,429,4312,...,26,30,6,9,11,17,0,17,11,17
892,1400000US06077005135,06077005135,"Census Tract 51.35, San Joaquin County, Califo...",7231,399,5341,512,1890,493,6573,...,32,38,0,17,11,17,11,17,0,17
893,1400000US06077005202,06077005202,"Census Tract 52.02, San Joaquin County, Califo...",7371,497,5173,577,2198,563,6595,...,0,17,44,98,13,17,13,17,0,17
894,1400000US06077005206,06077005206,"Census Tract 52.06, San Joaquin County, Califo...",21584,1127,14938,1487,6646,1368,18780,...,0,23,18,33,203,167,137,125,66,105
895,1400000US06077005207,06077005207,"Census Tract 52.07, San Joaquin County, Califo...",14594,739,11119,1109,3475,1008,12157,...,122,146,0,19,182,163,150,159,32,52
896,1400000US06077005208,06077005208,"Census Tract 52.08, San Joaquin County, Califo...",6134,413,4328,442,1806,559,5418,...,0,17,24,38,0,17,0,17,0,17
897,1400000US06077005209,06077005209,"Census Tract 52.09, San Joaquin County, Califo...",7348,323,5618,498,1730,435,6405,...,21,25,0,17,92,116,77,114,15,22
898,1400000US06077005210,06077005210,"Census Tract 52.10, San Joaquin County, Califo...",11915,564,8417,827,3498,810,10851,...,0,19,241,207,66,62,66,62,0,19
899,1400000US06077005302,06077005302,"Census Tract 53.02, San Joaquin County, Califo...",7183,549,3410,763,3773,910,5699,...,0,17,12,20,20,32,20,32,0,17
900,1400000US06077005303,06077005303,"Census Tract 53.03, San Joaquin County, Califo...",4771,425,1117,232,3654,482,3831,...,11,16,12,18,0,12,0,12,0,12
901,1400000US06077005305,06077005305,"Census Tract 53.05, San Joaquin County, Califo...",6517,509,2770,443,3747,674,5458,...,46,82,204,170,14,23,14,23,0,17
902,1400000US06077005307,06077005307,"Census Tract 53.07, San Joaquin County, Califo...",3155,231,1103,205,2052,285,2528,...,4,8,83,52,11,14,11,14,0,12
903,1400000US06077005308,06077005308,"Census Tract 53.08, San Joaquin County, Califo...",4169,297,2416,371,1753,415,3704,...,0,12,0,12,6,9,6,9,0,12
904,1400000US06077005403,06077005403,"Census Tract 54.03, San Joaquin County, Califo...",6208,482,4225,499,1983,563,5649,...,79,119,0,17,0,17,0,17,0,17
905,1400000US06077005405,06077005405,"Census Tract 54.05, San Joaquin County, Califo...",3280,281,1451,335,1829,340,2984,...,10,15,10,15,43,57,43,57,0,12
906,1400000US06077005406,06077005406,"Census Tract 54.06, San Joaquin County, Califo...",3500,244,1397,284,2103,320,2979,...,6,8,4,6,27,29,27,29,0,12
907,1400000US06077005501,06077005501,"Census Tract 55.01, San Joaquin County, Califo...",1613,203,1052,141,561,173,1419,...,4,6,0,12,3,4,3,4,0,12
908,1400000US06077005502,06077005502,"Census Tract 55.02, San Joaquin County, Califo...",1975,176,1252,170,723,220,1702,...,0,12,101,155,0,12,0,12,0,12

We can see that there are 909 rows in the data, and each row has 39 columns. The first column is the index. The index is used to identify the position of the data, but it is not an actual column. It looks like the read_csv function in Pandas read our file properly. However, we haven’t saved any data to memory so we can work with it. We need to assign the data to an object. We can create a new object with a name by assigning a value to it using "=".

In [36]:
mobility_df=pd.read_csv('ACS_17_5YR_B07013_with_ann.csv', delimiter = ',', header=[0], skiprows=[1], dtype=dtypes)

In [ ]:
#write the code to see the data here, ideally just five rows

In [ ]:
#if I want to know the kind of object I've just created, I can type "type(name)"
type(mobility_df)

In [ ]:
#if I want to see whether my datatypes imported correctly, I can type (name.dtypes)
mobility_df.dtypes

### 1.3 Renaming our Variables

I am now going to write some code to rename my columns into something that is more intuitive for me to type.  I can do this in the .csv first, but I like this approach because then I can run it again for different geographies/different years in the future.  See my example Excel sheet for my approach to doing this efficiently!

As in the above example, I am going to create a dictionary file (with the curly brackets), and assign the new name to each old name.  I will use the function "rename".  The inplace="True" command tells Python to overwrite the dataframe with the new names.

In [37]:
mobility_df.rename(columns={"GEO.id":"fullfips","GEO.id2":"fips",
"GEO.display-label":"label",
"HD01_VD01":"tot",
"HD02_VD01":"tot_moe",
"HD01_VD03":"owner",
"HD02_VD03":"owner_moe",
"HD01_VD04":"renter",
"HD02_VD04":"renter_moe",
"HD01_VD05":"tot_samehouse",
"HD02_VD05":"tot_samehouse_moe",
"HD01_VD06":"owner_samehouse",
"HD02_VD06":"owner_samehouse_moe",
"HD01_VD07":"renter_samehouse",
"HD02_VD07":"renter_samehouse_moe",
"HD01_VD08":"tot_cty",
"HD02_VD08":"tot_cty_moe",
"HD01_VD09":"owner_cty",
"HD02_VD09":"owner_cty_moe",
"HD01_VD10":"renter_cty",
"HD02_VD10":"renter_cty_moe",
"HD01_VD11":"tot_dcty",
"HD02_VD11":"tot_dcty_moe",
"HD01_VD12":"owner_dcty",
"HD02_VD12":"owner_dcty_moe",
"HD01_VD13":"renter_dcty",
"HD02_VD13":"renter_dcty_moe",
"HD01_VD14":"tot_state",
"HD02_VD14":"tot_state_moe",
"HD01_VD15":"owner_state",
"HD02_VD15":"owner_state_moe",
"HD01_VD16":"renter_state",
"HD02_VD16":"renter_state_moe",
"HD01_VD17":"tot_abroad",
"HD02_VD17":"tot_abroad_moe",
"HD01_VD18":"owner_abroad",
"HD02_VD18":"owner_abroad_moe",
"HD01_VD19":"renter_abroad",
"HD02_VD19":"renter_abroad_moe"}, inplace=True)

It's always good practice to check and make sure your code ran correctly.  Check to see if your column names showed up the way you wanted, and that you're dataset is in good shape!

In [38]:
mobility_df.columns

Index(['fullfips', 'fips', 'label', 'tot', 'tot_moe', 'owner', 'owner_moe',
       'renter', 'renter_moe', 'tot_samehouse', 'tot_samehouse_moe',
       'owner_samehouse', 'owner_samehouse_moe', 'renter_samehouse',
       'renter_samehouse_moe', 'tot_cty', 'tot_cty_moe', 'owner_cty',
       'owner_cty_moe', 'renter_cty', 'renter_cty_moe', 'tot_dcty',
       'tot_dcty_moe', 'owner_dcty', 'owner_dcty_moe', 'renter_dcty',
       'renter_dcty_moe', 'tot_state', 'tot_state_moe', 'owner_state',
       'owner_state_moe', 'renter_state', 'renter_state_moe', 'tot_abroad',
       'tot_abroad_moe', 'owner_abroad', 'owner_abroad_moe', 'renter_abroad',
       'renter_abroad_moe'],
      dtype='object')

In [39]:
mobility_df

,fullfips,fips,label,tot,tot_moe,owner,owner_moe,renter,renter_moe,tot_samehouse,...,owner_state,owner_state_moe,renter_state,renter_state_moe,tot_abroad,tot_abroad_moe,owner_abroad,owner_abroad_moe,renter_abroad,renter_abroad_moe
0,0500000US06001,06001,"Alameda County, California",1578306,1317,876019,7381,702287,7464,1378727,...,5375,628,16635,1336,20040,1116,6019,621,14021,996
1,0500000US06013,06013,"Contra Costa County, California",1101965,850,722925,6012,379040,6076,957822,...,5462,718,7339,909,9945,1204,4364,587,5581,1054
2,0500000US06075,06075,"San Francisco County, California",834977,1120,362591,4685,472386,4717,724483,...,2800,432,16557,1088,12395,1228,2634,503,9761,1052
3,0500000US06077,06077,"San Joaquin County, California",699091,1401,386343,6073,312748,5944,596731,...,1894,575,4867,820,3460,678,1921,558,1539,450
4,1400000US06001400100,06001400100,"Census Tract 4001, Alameda County, California",2953,189,2621,228,332,171,2418,...,91,99,67,91,30,31,30,31,0,12
5,1400000US06001400200,06001400200,"Census Tract 4002, Alameda County, California",1889,89,1154,115,735,115,1694,...,0,12,28,27,41,47,31,44,10,11
6,1400000US06001400300,06001400300,"Census Tract 4003, Alameda County, California",5050,303,2708,375,2342,360,4380,...,11,19,131,105,35,41,0,17,35,41
7,1400000US06001400400,06001400400,"Census Tract 4004, Alameda County, California",3820,232,1591,283,2229,344,3296,...,8,15,87,69,9,15,0,12,9,15
8,1400000US06001400500,06001400500,"Census Tract 4005, Alameda County, California",3864,308,1474,277,2390,341,3000,...,8,12,161,105,36,36,0,12,36,36
9,1400000US06001400600,06001400600,"Census Tract 4006, Alameda County, California",1580,174,886,187,694,140,1200,...,17,20,93,88,0,12,0,12,0,12
10,1400000US06001400700,06001400700,"Census Tract 4007, Alameda County, California",4753,487,1982,407,2771,509,4016,...,25,32,142,71,34,45,0,12,34,45
11,1400000US06001400800,06001400800,"Census Tract 4008, Alameda County, California",3665,363,1150,325,2515,505,3058,...,0,12,99,87,43,48,0,12,43,48
12,1400000US06001400900,06001400900,"Census Tract 4009, Alameda County, California",2377,189,814,171,1563,227,2097,...,0,12,56,53,0,12,0,12,0,12
13,1400000US06001401000,06001401000,"Census Tract 4010, Alameda County, California",6210,474,2127,525,4083,606,5438,...,0,17,117,112,20,31,0,17,20,31
14,1400000US06001401100,06001401100,"Census Tract 4011, Alameda County, California",4072,315,1039,282,3033,402,2999,...,42,58,178,171,27,44,0,12,27,44
15,1400000US06001401200,06001401200,"Census Tract 4012, Alameda County, California",2580,186,1143,209,1437,221,2140,...,0,12,57,69,0,12,0,12,0,12
16,1400000US06001401300,06001401300,"Census Tract 4013, Alameda County, California",3344,583,654,208,2690,568,2380,...,28,32,113,60,45,49,25,38,20,28
17,1400000US06001401400,06001401400,"Census Tract 4014, Alameda County, California",3725,415,635,274,3090,407,3188,...,0,12,26,29,31,36,0,12,31,36
18,1400000US06001401500,06001401500,"Census Tract 4015, Alameda County, California",2618,294,970,223,1648,278,1958,...,0,12,7,10,26,26,6,9,20,24
19,1400000US06001401600,06001401600,"Census Tract 4016, Alameda County, California",2016,197,483,146,1533,226,1630,...,6,9,5,8,23,28,0,12,23,28
20,1400000US06001401700,06001401700,"Census Tract 4017, Alameda County, California",2653,353,1312,301,1341,352,2299,...,0,12,10,15,0,12,0,12,0,12
21,1400000US06001401800,06001401800,"Census Tract 4018, Alameda County, California",1916,269,373,121,1543,268,1461,...,0,12,93,85,7,12,0,12,7,12
22,1400000US06001402200,06001402200,"Census Tract 4022, Alameda County, California",2512,192,876,190,1636,236,2158,...,0,12,35,27,21,24,9,13,12,20
23,1400000US06001402400,06001402400,"Census Tract 4024, Alameda County, California",2772,315,750,220,2022,261,2489,...,31,31,0,12,0,12,0,12,0,12
24,1400000US06001402500,06001402500,"Census Tract 4025, Alameda County, California",1737,184,250,140,1487,187,1601,...,0,12,0,12,0,12,0,12,0,12
25,1400000US06001402600,06001402600,"Census Tract 4026, Alameda County, California",1236,92,169,63,1067,95,1036,...,0,12,33,51,68,62,0,12,68,62
26,1400000US06001402700,06001402700,"Census Tract 4027, Alameda County, California",1805,206,429,139,1376,214,1251,...,8,11,33,26,0,12,0,12,0,12
27,1400000US06001402800,06001402800,"Census Tract 4028, Alameda County, California",3900,270,289,129,3611,266,2491,...,0,12,127,110,26,31,0,12,26,31
28,1400000US06001402900,06001402900,"Census Tract 4029, Alameda County, California",1294,94,21,30,1273,89,1092,...,0,12,42,29,12,17,0,12,12,17
29,1400000US06001403000,06001403000,"Census Tract 4030, Alameda County, California",3148,235,804,245,2344,265,2748,...,0,12,0,12,151,99,26,41,125,105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
879,1400000US06077005119,06077005119,"Census Tract 51.19, San Joaquin County, Califo...",8047,432,5059,646,2988,827,6684,...,0,17,67,91,271,221,80,100,191,207
880,1400000US06077005122,06077005122,"Census Tract 51.22, San Joaquin County, Califo...",6305,507,4504,660,1801,472,5311,...,0,17,32,51,0,17,0,17,0,17
881,1400000US06077005123,06077005123,"Census Tract 51.23, San Joaquin County, Califo...",4552,333,2827,371,1725,388,3819,...,0,12,26,42,13,20,0,12,13,20
882,1400000US06077005124,06077005124,"Census Tract 51.24, San Joaquin County, Califo...",3201,288,1532,282,1669,312,2531,...,0,12,28,33,37,57,0,12,37,57
883,1400000US06077005125,06077005125,"Census Tract 51.25, San Joaquin County, Califo...",1879,122,1038,241,841,221,1697,...,8,12,0,12,8,12,8,12,0,12
884,1400000US06077005126,06077005126,"Census Tract 51.26, San Joaquin County, Califo...",3961,378,1918,392,2043,457,3349,...,10,17,0,12,86,99,0,12,86,99
885,1400000US06077005127,06077005127,"Census Tract 51.27, San Joaquin County, Califo...",5926,312,4387,444,1539,454,5186,...,0,17,0,17,97,55,81,54,16,19
886,1400000US06077005129,06077005129,"Census Tract 51.29, San Joaquin County, Califo...",3497,279,2510,366,987,390,3166,...,10,15,0,12,0,12,0,12,0,12
887,1400000US06077005130,06077005130,"Census Tract 51.30, San Joaquin County, Califo...",3389,300,2017,353,1372,342,2772,...,0,12,0,12,19,28,6,10,13,21
888,1400000US06077005131,06077005131,"Census Tract 51.31, San Joaquin County, Califo...",4344,601,2554,452,1790,601,3973,...,0,17,0,17,6,12,6,12,0,17
889,1400000US06077005132,06077005132,"Census Tract 51.32, San Joaquin County, Califo...",3112,332,1530,340,1582,424,2343,...,0,12,89,104,23,41,0,12,23,41
890,1400000US06077005133,06077005133,"Census Tract 51.33, San Joaquin County, Califo...",3859,359,2110,420,1749,492,3144,...,0,12,62,94,14,21,14,21,0,12
891,1400000US06077005134,06077005134,"Census Tract 51.34, San Joaquin County, Califo...",5024,261,2694,437,2330,429,4312,...,26,30,6,9,11,17,0,17,11,17
892,1400000US06077005135,06077005135,"Census Tract 51.35, San Joaquin County, Califo...",7231,399,5341,512,1890,493,6573,...,32,38,0,17,11,17,11,17,0,17
893,1400000US06077005202,06077005202,"Census Tract 52.02, San Joaquin County, Califo...",7371,497,5173,577,2198,563,6595,...,0,17,44,98,13,17,13,17,0,17
894,1400000US06077005206,06077005206,"Census Tract 52.06, San Joaquin County, Califo...",21584,1127,14938,1487,6646,1368,18780,...,0,23,18,33,203,167,137,125,66,105
895,1400000US06077005207,06077005207,"Census Tract 52.07, San Joaquin County, Califo...",14594,739,11119,1109,3475,1008,12157,...,122,146,0,19,182,163,150,159,32,52
896,1400000US06077005208,06077005208,"Census Tract 52.08, San Joaquin County, Califo...",6134,413,4328,442,1806,559,5418,...,0,17,24,38,0,17,0,17,0,17
897,1400000US06077005209,06077005209,"Census Tract 52.09, San Joaquin County, Califo...",7348,323,5618,498,1730,435,6405,...,21,25,0,17,92,116,77,114,15,22
898,1400000US06077005210,06077005210,"Census Tract 52.10, San Joaquin County, Califo...",11915,564,8417,827,3498,810,10851,...,0,19,241,207,66,62,66,62,0,19
899,1400000US06077005302,06077005302,"Census Tract 53.02, San Joaquin County, Califo...",7183,549,3410,763,3773,910,5699,...,0,17,12,20,20,32,20,32,0,17
900,1400000US06077005303,06077005303,"Census Tract 53.03, San Joaquin County, Califo...",4771,425,1117,232,3654,482,3831,...,11,16,12,18,0,12,0,12,0,12
901,1400000US06077005305,06077005305,"Census Tract 53.05, San Joaquin County, Califo...",6517,509,2770,443,3747,674,5458,...,46,82,204,170,14,23,14,23,0,17
902,1400000US06077005307,06077005307,"Census Tract 53.07, San Joaquin County, Califo...",3155,231,1103,205,2052,285,2528,...,4,8,83,52,11,14,11,14,0,12
903,1400000US06077005308,06077005308,"Census Tract 53.08, San Joaquin County, Califo...",4169,297,2416,371,1753,415,3704,...,0,12,0,12,6,9,6,9,0,12
904,1400000US06077005403,06077005403,"Census Tract 54.03, San Joaquin County, Califo...",6208,482,4225,499,1983,563,5649,...,79,119,0,17,0,17,0,17,0,17
905,1400000US06077005405,06077005405,"Census Tract 54.05, San Joaquin County, Califo...",3280,281,1451,335,1829,340,2984,...,10,15,10,15,43,57,43,57,0,12
906,1400000US06077005406,06077005406,"Census Tract 54.06, San Joaquin County, Califo...",3500,244,1397,284,2103,320,2979,...,6,8,4,6,27,29,27,29,0,12
907,1400000US06077005501,06077005501,"Census Tract 55.01, San Joaquin County, Califo...",1613,203,1052,141,561,173,1419,...,4,6,0,12,3,4,3,4,0,12
908,1400000US06077005502,06077005502,"Census Tract 55.02, San Joaquin County, Califo...",1975,176,1252,170,723,220,1702,...,0,12,101,155,0,12,0,12,0,12

## 2 Working with our Dataset in Python

We're going to step back for a minute and spend a bit more time explaining how dataframe objects work in Python.  We often want to work with subsets of our data (e.g., just certain columns or variables).  In Python, this is referred to as "indexing" and "slicing".

### 2.1 Selecting Data Using Columns

We use square brackets [] to select a subset of a Python object.  For example, I can select just my fips code from the mobility_df dataframe by name.

You can also call an attribute of a dataframe by using the "dataframename.attribute" syntax.  Note that this doesn't work if you have spaces in your column names.

In [40]:
#the codes in the next two cells do the same thing.
mobility_df["fips"]

0            06001
1            06013
2            06075
3            06077
4      06001400100
5      06001400200
6      06001400300
7      06001400400
8      06001400500
9      06001400600
10     06001400700
11     06001400800
12     06001400900
13     06001401000
14     06001401100
15     06001401200
16     06001401300
17     06001401400
18     06001401500
19     06001401600
20     06001401700
21     06001401800
22     06001402200
23     06001402400
24     06001402500
25     06001402600
26     06001402700
27     06001402800
28     06001402900
29     06001403000
          ...
879    06077005119
880    06077005122
881    06077005123
882    06077005124
883    06077005125
884    06077005126
885    06077005127
886    06077005129
887    06077005130
888    06077005131
889    06077005132
890    06077005133
891    06077005134
892    06077005135
893    06077005202
894    06077005206
895    06077005207
896    06077005208
897    06077005209
898    06077005210
899    06077005302
900    06077005303
901    06077005305
902    06077005307
903    06077005308
904    06077005403
905    06077005405
906    06077005406
907    06077005501
908    06077005502
Name: fips, Length: 909, dtype: object

In [41]:
mobility_df.fips

0            06001
1            06013
2            06075
3            06077
4      06001400100
5      06001400200
6      06001400300
7      06001400400
8      06001400500
9      06001400600
10     06001400700
11     06001400800
12     06001400900
13     06001401000
14     06001401100
15     06001401200
16     06001401300
17     06001401400
18     06001401500
19     06001401600
20     06001401700
21     06001401800
22     06001402200
23     06001402400
24     06001402500
25     06001402600
26     06001402700
27     06001402800
28     06001402900
29     06001403000
          ...
879    06077005119
880    06077005122
881    06077005123
882    06077005124
883    06077005125
884    06077005126
885    06077005127
886    06077005129
887    06077005130
888    06077005131
889    06077005132
890    06077005133
891    06077005134
892    06077005135
893    06077005202
894    06077005206
895    06077005207
896    06077005208
897    06077005209
898    06077005210
899    06077005302
900    06077005303
901    06077005305
902    06077005307
903    06077005308
904    06077005403
905    06077005405
906    06077005406
907    06077005501
908    06077005502
Name: fips, Length: 909, dtype: object

I can also assign an object to this function.  For example, I can call this object fips_column. What type of object is it?

In [42]:
fips_column=mobility_df["fips"]

In [43]:
type(fips_column)

pandas.core.series.Series

In [45]:
# Can you see what is different from the code below to the code above? 

fips_column=mobility_df[["fips"]]
type(fips_column)

pandas.core.frame.DataFrame

This is what we tried to do last week, by selecting a few variables. But our code got us a warning message when we created a variable.

I mistakenly thought the code created a new copy of the mobility_df DataFrame object. However, using the = operator in a simple statement y = x does not create a copy of our DataFrame. Instead, y = x creates a new object y that references the same object that x refers to. To state this another way, there is only one object (the DataFrame), and both x and y refer to it.

An easy way to fix this is to make a copy of our dataframe. It really is like making a copy of your Excel worksheet and then just keeping some of the columns.

In [46]:
new_mobility_df=mobility_df[["fips","tot", "owner"]].copy()

Now, you should be able to make new variables without a data error.

In [47]:
new_mobility_df["pct_owner"]=new_mobility_df["owner"]/new_mobility_df["tot"]*100
new_mobility_df

            fips      tot   owner  pct_owner
0          06001  1578306  876019      55.50
1          06013  1101965  722925      65.60
2          06075   834977  362591      43.43
3          06077   699091  386343      55.26
4    06001400100     2953    2621      88.76
5    06001400200     1889    1154      61.09
6    06001400300     5050    2708      53.62
7    06001400400     3820    1591      41.65
8    06001400500     3864    1474      38.15
9    06001400600     1580     886      56.08
10   06001400700     4753    1982      41.70
11   06001400800     3665    1150      31.38
12   06001400900     2377     814      34.24
13   06001401000     6210    2127      34.25
14   06001401100     4072    1039      25.52
15   06001401200     2580    1143      44.30
16   06001401300     3344     654      19.56
17   06001401400     3725     635      17.05
18   06001401500     2618     970      37.05
19   06001401600     2016     483      23.96
20   06001401700     2653    1312      49.45
21   06001401800     1916     373      19.47
22   06001402200     2512     876      34.87
23   06001402400     2772     750      27.06
24   06001402500     1737     250      14.39
25   06001402600     1236     169      13.67
26   06001402700     1805     429      23.77
27   06001402800     3900     289       7.41
28   06001402900     1294      21       1.62
29   06001403000     3148     804      25.54
..           ...      ...     ...        ...
879  06077005119     8047    5059      62.87
880  06077005122     6305    4504      71.44
881  06077005123     4552    2827      62.10
882  06077005124     3201    1532      47.86
883  06077005125     1879    1038      55.24
884  06077005126     3961    1918      48.42
885  06077005127     5926    4387      74.03
886  06077005129     3497    2510      71.78
887  06077005130     3389    2017      59.52
888  06077005131     4344    2554      58.79
889  06077005132     3112    1530      49.16
890  06077005133     3859    2110      54.68
891  06077005134     5024    2694      53.62
892  06077005135     7231    5341      73.86
893  06077005202     7371    5173      70.18
894  06077005206    21584   14938      69.21
895  06077005207    14594   11119      76.19
896  06077005208     6134    4328      70.56
897  06077005209     7348    5618      76.46
898  06077005210    11915    8417      70.64
899  06077005302     7183    3410      47.47
900  06077005303     4771    1117      23.41
901  06077005305     6517    2770      42.50
902  06077005307     3155    1103      34.96
903  06077005308     4169    2416      57.95
904  06077005403     6208    4225      68.06
905  06077005405     3280    1451      44.24
906  06077005406     3500    1397      39.91
907  06077005501     1613    1052      65.22
908  06077005502     1975    1252      63.39

[909 rows x 4 columns]

### 2.2 Selecting Data with Pandas

Ok!  Now we're getting somewhere.  What if we want to subset our data using rows, for example, making a separate dataframe for the county rows or selecting just our case study census tracts?

Let’s remind ourselves that Python uses 0-based indexing. This means that the first row in a dataframe (really, in any object or series) is located at position 0.  This is different from Excel which starts with the number 1.

Slicing using the [ ] operator selects a set of rows and/or columns from a DataFrame. To slice out a set of rows, you use the following syntax: data[start position:stop position]. When slicing in pandas the start bound is included in the output. The stop bound is one step BEYOND the row you want to select. So if you want to select rows 0, 1 and 2 your code would look like this:

In [ ]:
new_mobility_df[0:3]

We can become more specific and select our data by columns and rows With the functions .loc and .iloc. .loc is label-based, which means that you have to specify rows and columns based on their row and column labels (it stands for "location"). .iloc is integer index based, so you have to specify rows and columns by their integer index like you did in the previous exercise.

In [ ]:
#Note that in this dataset, our row "labels" are the index numbers, so in this case,
#for rows, .loc and .iloc look the same
new_mobility_df.loc[0, "tot"]

In [ ]:
new_mobility_df.iloc[0, 1]

In [ ]:
# in this cell, try and call up pct owners in San Francisco county (fips = 06075), 
# using both the .loc and .iloc commands

We can also include ranges.

In [ ]:
new_mobility_df.loc[[0, 10], "tot"]

In [ ]:
new_mobility_df.loc[0:10, ["tot", "owner"]]

In [ ]:
# in this cell, try and call the first three columns and the first 10 rows using iloc instead.

### 2.3 Working with Conditional Statements

When we start working with our data, we want to treat our counties separately from our census tracts, otherwise, we might accidentally add the county values to our calculations.  Let's create a new dataframe with just our county data, and drop the county rows from our datasheet.  We do this with a "conditional" statement.  As a reminder, conditional operators are:

**< less than**
   
**<= less than or equivalent to**
   
**> more than**
   
**>= more than or equivalent to**
   
**== equivalent to**

**!= not equivalent to**

If we want to combine more than one conditional statement, we'll use

**& for "and"**

**| for "or"**

In [48]:
# Here, I want to create a new dataframe, that includes just the data for the four Bay Area Counties
counties=mobility_df[(mobility_df.fips=="06001") 
                         | (mobility_df.fips=="06013")
                         | (mobility_df.fips=="06075")
                         | (mobility_df.fips=="06077")].copy()

In [49]:
counties

,fullfips,fips,label,tot,tot_moe,owner,owner_moe,renter,renter_moe,tot_samehouse,...,owner_state,owner_state_moe,renter_state,renter_state_moe,tot_abroad,tot_abroad_moe,owner_abroad,owner_abroad_moe,renter_abroad,renter_abroad_moe
0,0500000US06001,06001,"Alameda County, California",1578306,1317,876019,7381,702287,7464,1378727,...,5375,628,16635,1336,20040,1116,6019,621,14021,996
1,0500000US06013,06013,"Contra Costa County, California",1101965,850,722925,6012,379040,6076,957822,...,5462,718,7339,909,9945,1204,4364,587,5581,1054
2,0500000US06075,06075,"San Francisco County, California",834977,1120,362591,4685,472386,4717,724483,...,2800,432,16557,1088,12395,1228,2634,503,9761,1052
3,0500000US06077,06077,"San Joaquin County, California",699091,1401,386343,6073,312748,5944,596731,...,1894,575,4867,820,3460,678,1921,558,1539,450

I am now going to drop my county rows from my mobility_df dataframe, so I can calcuate statistics for census tracts without inadvertantly adding in the county data.

In [50]:
# Dropping county rows.  There's lots of ways to do this, and we'll get more sophisticated
# later, but for now, we're just going to tell it to trop the first four rows.
# We have to use "inplace=True" because otherwise Python won't overwrite the original dataframe.
mobility_df.drop([0, 1, 2, 3], inplace=True)

## 3. Aggregating MOEs and Testing for Statistical Significance

Now, we're going to go through the same steps as we did in Excel to calculate values for our case study, and compare them to the county.  I want to know whether the percent of people who lived in the same house a year ago in Downtown Oakland is the same or different from the percent of the population who lived in the same house one year ago in Alameda County. I also want to see what share of people "in-migrated" to my neighborhood, by adding up the number of people who moved in from out of the county, out of the state, or from abroad.

Create a markdown cell under this one to write out the steps we did in Excel when we wanted to do this.

### 3.1  Create a Dummy Variable

First, we need to create a dummy variable, so we can calculate the statistics for our case study.  We're going to use a conditional statement again, but this time, we're going to use our numpy library to assign a 1 to every tract that meets the condition, and 0 to every tract where the conditions aren't met.

In [61]:
mobility_df["downtown_oakland"]=np.where(((mobility_df["fips"]=="06001402800") 
                         | (mobility_df["fips"]=="06001402900")
                         | (mobility_df["fips"]=="06001403000")
                         | (mobility_df["fips"]=="06001403100")
                         | (mobility_df["fips"]=="06001403300")
                         | (mobility_df["fips"]=="06001983200")), 1,0)

In [ ]:
#Test to see if it worked, printing just the fips code and the downtown_oakland variable

In [ ]:
#In this cell, create a dummy for your census tracts.  We've included Alameda, Contra Costa, 
# San Francisco, and San Joaquin data in the datasheet.

### 3.2 Aggregating Totals Across Rows

Luckily, I don't need to aggregate any data for the people who lived in the same house - that's just one column of data.  But I do for my "in-migrant" column.

In [52]:
# Running my column names here makes it so I don't have to scroll up to see my names.
print(mobility_df.columns)
mobility_df

Index(['fullfips', 'fips', 'label', 'tot', 'tot_moe', 'owner', 'owner_moe',
       'renter', 'renter_moe', 'tot_samehouse', 'tot_samehouse_moe',
       'owner_samehouse', 'owner_samehouse_moe', 'renter_samehouse',
       'renter_samehouse_moe', 'tot_cty', 'tot_cty_moe', 'owner_cty',
       'owner_cty_moe', 'renter_cty', 'renter_cty_moe', 'tot_dcty',
       'tot_dcty_moe', 'owner_dcty', 'owner_dcty_moe', 'renter_dcty',
       'renter_dcty_moe', 'tot_state', 'tot_state_moe', 'owner_state',
       'owner_state_moe', 'renter_state', 'renter_state_moe', 'tot_abroad',
       'tot_abroad_moe', 'owner_abroad', 'owner_abroad_moe', 'renter_abroad',
       'renter_abroad_moe'],
      dtype='object')

,fullfips,fips,label,tot,tot_moe,owner,owner_moe,renter,renter_moe,tot_samehouse,...,owner_state,owner_state_moe,renter_state,renter_state_moe,tot_abroad,tot_abroad_moe,owner_abroad,owner_abroad_moe,renter_abroad,renter_abroad_moe
4,1400000US06001400100,06001400100,"Census Tract 4001, Alameda County, California",2953,189,2621,228,332,171,2418,...,91,99,67,91,30,31,30,31,0,12
5,1400000US06001400200,06001400200,"Census Tract 4002, Alameda County, California",1889,89,1154,115,735,115,1694,...,0,12,28,27,41,47,31,44,10,11
6,1400000US06001400300,06001400300,"Census Tract 4003, Alameda County, California",5050,303,2708,375,2342,360,4380,...,11,19,131,105,35,41,0,17,35,41
7,1400000US06001400400,06001400400,"Census Tract 4004, Alameda County, California",3820,232,1591,283,2229,344,3296,...,8,15,87,69,9,15,0,12,9,15
8,1400000US06001400500,06001400500,"Census Tract 4005, Alameda County, California",3864,308,1474,277,2390,341,3000,...,8,12,161,105,36,36,0,12,36,36
9,1400000US06001400600,06001400600,"Census Tract 4006, Alameda County, California",1580,174,886,187,694,140,1200,...,17,20,93,88,0,12,0,12,0,12
10,1400000US06001400700,06001400700,"Census Tract 4007, Alameda County, California",4753,487,1982,407,2771,509,4016,...,25,32,142,71,34,45,0,12,34,45
11,1400000US06001400800,06001400800,"Census Tract 4008, Alameda County, California",3665,363,1150,325,2515,505,3058,...,0,12,99,87,43,48,0,12,43,48
12,1400000US06001400900,06001400900,"Census Tract 4009, Alameda County, California",2377,189,814,171,1563,227,2097,...,0,12,56,53,0,12,0,12,0,12
13,1400000US06001401000,06001401000,"Census Tract 4010, Alameda County, California",6210,474,2127,525,4083,606,5438,...,0,17,117,112,20,31,0,17,20,31
14,1400000US06001401100,06001401100,"Census Tract 4011, Alameda County, California",4072,315,1039,282,3033,402,2999,...,42,58,178,171,27,44,0,12,27,44
15,1400000US06001401200,06001401200,"Census Tract 4012, Alameda County, California",2580,186,1143,209,1437,221,2140,...,0,12,57,69,0,12,0,12,0,12
16,1400000US06001401300,06001401300,"Census Tract 4013, Alameda County, California",3344,583,654,208,2690,568,2380,...,28,32,113,60,45,49,25,38,20,28
17,1400000US06001401400,06001401400,"Census Tract 4014, Alameda County, California",3725,415,635,274,3090,407,3188,...,0,12,26,29,31,36,0,12,31,36
18,1400000US06001401500,06001401500,"Census Tract 4015, Alameda County, California",2618,294,970,223,1648,278,1958,...,0,12,7,10,26,26,6,9,20,24
19,1400000US06001401600,06001401600,"Census Tract 4016, Alameda County, California",2016,197,483,146,1533,226,1630,...,6,9,5,8,23,28,0,12,23,28
20,1400000US06001401700,06001401700,"Census Tract 4017, Alameda County, California",2653,353,1312,301,1341,352,2299,...,0,12,10,15,0,12,0,12,0,12
21,1400000US06001401800,06001401800,"Census Tract 4018, Alameda County, California",1916,269,373,121,1543,268,1461,...,0,12,93,85,7,12,0,12,7,12
22,1400000US06001402200,06001402200,"Census Tract 4022, Alameda County, California",2512,192,876,190,1636,236,2158,...,0,12,35,27,21,24,9,13,12,20
23,1400000US06001402400,06001402400,"Census Tract 4024, Alameda County, California",2772,315,750,220,2022,261,2489,...,31,31,0,12,0,12,0,12,0,12
24,1400000US06001402500,06001402500,"Census Tract 4025, Alameda County, California",1737,184,250,140,1487,187,1601,...,0,12,0,12,0,12,0,12,0,12
25,1400000US06001402600,06001402600,"Census Tract 4026, Alameda County, California",1236,92,169,63,1067,95,1036,...,0,12,33,51,68,62,0,12,68,62
26,1400000US06001402700,06001402700,"Census Tract 4027, Alameda County, California",1805,206,429,139,1376,214,1251,...,8,11,33,26,0,12,0,12,0,12
27,1400000US06001402800,06001402800,"Census Tract 4028, Alameda County, California",3900,270,289,129,3611,266,2491,...,0,12,127,110,26,31,0,12,26,31
28,1400000US06001402900,06001402900,"Census Tract 4029, Alameda County, California",1294,94,21,30,1273,89,1092,...,0,12,42,29,12,17,0,12,12,17
29,1400000US06001403000,06001403000,"Census Tract 4030, Alameda County, California",3148,235,804,245,2344,265,2748,...,0,12,0,12,151,99,26,41,125,105
30,1400000US06001403100,06001403100,"Census Tract 4031, Alameda County, California",1281,86,362,94,919,107,1074,...,12,16,42,34,16,25,0,12,16,25
31,1400000US06001403300,06001403300,"Census Tract 4033, Alameda County, California",4728,421,643,204,4085,469,3727,...,59,93,311,164,102,119,0,12,102,119
32,1400000US06001403400,06001403400,"Census Tract 4034, Alameda County, California",4360,350,394,136,3966,349,3344,...,0,12,226,124,7,12,0,12,7,12
33,1400000US06001403501,06001403501,"Census Tract 4035.01, Alameda County, California",4642,328,716,270,3926,425,3781,...,0,12,118,82,12,20,0,12,12,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
879,1400000US06077005119,06077005119,"Census Tract 51.19, San Joaquin County, Califo...",8047,432,5059,646,2988,827,6684,...,0,17,67,91,271,221,80,100,191,207
880,1400000US06077005122,06077005122,"Census Tract 51.22, San Joaquin County, Califo...",6305,507,4504,660,1801,472,5311,...,0,17,32,51,0,17,0,17,0,17
881,1400000US06077005123,06077005123,"Census Tract 51.23, San Joaquin County, Califo...",4552,333,2827,371,1725,388,3819,...,0,12,26,42,13,20,0,12,13,20
882,1400000US06077005124,06077005124,"Census Tract 51.24, San Joaquin County, Califo...",3201,288,1532,282,1669,312,2531,...,0,12,28,33,37,57,0,12,37,57
883,1400000US06077005125,06077005125,"Census Tract 51.25, San Joaquin County, Califo...",1879,122,1038,241,841,221,1697,...,8,12,0,12,8,12,8,12,0,12
884,1400000US06077005126,06077005126,"Census Tract 51.26, San Joaquin County, Califo...",3961,378,1918,392,2043,457,3349,...,10,17,0,12,86,99,0,12,86,99
885,1400000US06077005127,06077005127,"Census Tract 51.27, San Joaquin County, Califo...",5926,312,4387,444,1539,454,5186,...,0,17,0,17,97,55,81,54,16,19
886,1400000US06077005129,06077005129,"Census Tract 51.29, San Joaquin County, Califo...",3497,279,2510,366,987,390,3166,...,10,15,0,12,0,12,0,12,0,12
887,1400000US06077005130,06077005130,"Census Tract 51.30, San Joaquin County, Califo...",3389,300,2017,353,1372,342,2772,...,0,12,0,12,19,28,6,10,13,21
888,1400000US06077005131,06077005131,"Census Tract 51.31, San Joaquin County, Califo...",4344,601,2554,452,1790,601,3973,...,0,17,0,17,6,12,6,12,0,17
889,1400000US06077005132,06077005132,"Census Tract 51.32, San Joaquin County, Califo...",3112,332,1530,340,1582,424,2343,...,0,12,89,104,23,41,0,12,23,41
890,1400000US06077005133,06077005133,"Census Tract 51.33, San Joaquin County, Califo...",3859,359,2110,420,1749,492,3144,...,0,12,62,94,14,21,14,21,0,12
891,1400000US06077005134,06077005134,"Census Tract 51.34, San Joaquin County, Califo...",5024,261,2694,437,2330,429,4312,...,26,30,6,9,11,17,0,17,11,17
892,1400000US06077005135,06077005135,"Census Tract 51.35, San Joaquin County, Califo...",7231,399,5341,512,1890,493,6573,...,32,38,0,17,11,17,11,17,0,17
893,1400000US06077005202,06077005202,"Census Tract 52.02, San Joaquin County, Califo...",7371,497,5173,577,2198,563,6595,...,0,17,44,98,13,17,13,17,0,17
894,1400000US06077005206,06077005206,"Census Tract 52.06, San Joaquin County, Califo...",21584,1127,14938,1487,6646,1368,18780,...,0,23,18,33,203,167,137,125,66,105
895,1400000US06077005207,06077005207,"Census Tract 52.07, San Joaquin County, Califo...",14594,739,11119,1109,3475,1008,12157,...,122,146,0,19,182,163,150,159,32,52
896,1400000US06077005208,06077005208,"Census Tract 52.08, San Joaquin County, Califo...",6134,413,4328,442,1806,559,5418,...,0,17,24,38,0,17,0,17,0,17
897,1400000US06077005209,06077005209,"Census Tract 52.09, San Joaquin County, Califo...",7348,323,5618,498,1730,435,6405,...,21,25,0,17,92,116,77,114,15,22
898,1400000US06077005210,06077005210,"Census Tract 52.10, San Joaquin County, Califo...",11915,564,8417,827,3498,810,10851,...,0,19,241,207,66,62,66,62,0,19
899,1400000US06077005302,06077005302,"Census Tract 53.02, San Joaquin County, Califo...",7183,549,3410,763,3773,910,5699,...,0,17,12,20,20,32,20,32,0,17
900,1400000US06077005303,06077005303,"Census Tract 53.03, San Joaquin County, Califo...",4771,425,1117,232,3654,482,3831,...,11,16,12,18,0,12,0,12,0,12
901,1400000US06077005305,06077005305,"Census Tract 53.05, San Joaquin County, Califo...",6517,509,2770,443,3747,674,5458,...,46,82,204,170,14,23,14,23,0,17
902,1400000US06077005307,06077005307,"Census Tract 53.07, San Joaquin County, Califo...",3155,231,1103,205,2052,285,2528,...,4,8,83,52,11,14,11,14,0,12
903,1400000US06077005308,06077005308,"Census Tract 53.08, San Joaquin County, Califo...",4169,297,2416,371,1753,415,3704,...,0,12,0,12,6,9,6,9,0,12
904,1400000US06077005403,06077005403,"Census Tract 54.03, San Joaquin County, Califo...",6208,482,4225,499,1983,563,5649,...,79,119,0,17,0,17,0,17,0,17
905,1400000US06077005405,06077005405,"Census Tract 54.05, San Joaquin County, Califo...",3280,281,1451,335,1829,340,2984,...,10,15,10,15,43,57,43,57,0,12
906,1400000US06077005406,06077005406,"Census Tract 54.06, San Joaquin County, Califo...",3500,244,1397,284,2103,320,2979,...,6,8,4,6,27,29,27,29,0,12
907,1400000US06077005501,06077005501,"Census Tract 55.01, San Joaquin County, Califo...",1613,203,1052,141,561,173,1419,...,4,6,0,12,3,4,3,4,0,12
908,1400000US06077005502,06077005502,"Census Tract 55.02, San Joaquin County, Califo...",1975,176,1252,170,723,220,1702,...,0,12,101,155,0,12,0,12,0,12

In [57]:
# For my "different county or state" I need to first aggregate my "columns".
# Note how I print my input and output variables to check that it worked right.
mobility_df["tot_inmigrant"]= mobility_df["tot_dcty"]+mobility_df["tot_state"]+mobility_df["tot_abroad"]
mobility_df[["tot_dcty", "tot_state", "tot_abroad", "tot_inmigrant"]].head()

   tot_dcty  tot_state  tot_abroad  tot_inmigrant
4       112        158          30            300
5        62         28          41            131
6       275        142          35            452
7       294         95           9            398
8       340        169          36            545

In [ ]:
#Now I have to aggregate my MOEs. Square root sum of squares, right?  For square root, I have to call numpy.
# Try it yourself here

In [56]:
# Here's the equation for the square root sum of squares for my MOE
mobility_df["tot_inmigrant_moe"]= np.sqrt(mobility_df["tot_dcty_moe"]**2 + mobility_df["tot_state_moe"]**2
                                         + mobility_df["tot_abroad_moe"]**2)
mobility_df[["tot_dcty", "tot_state", "tot_abroad", "tot_inmigrant", 
             "tot_dcty_moe", "tot_state_moe", "tot_abroad_moe", "tot_inmigrant_moe"]].head()

,tot_dcty,tot_state,tot_abroad,tot_inmigrant,tot_dcty_moe,tot_state_moe,tot_abroad_moe,tot_inmigrant_moe
4,112,158,30,300,81,135,31,160.46
5,62,28,41,131,44,27,47,69.81
6,275,142,35,452,145,106,41,184.23
7,294,95,9,398,157,71,15,172.96
8,340,169,36,545,195,104,36,223.91

### 3.3  Aggregating the Data for Our Case Study Community

Now that we have a dummy variable, and our "summed" variables across columns, we can quickly summarize the data for our case study using Pandas “groupby()” functionality. Groupby essentially splits the data into different groups depending on a variable of your choice.

In [62]:
#this code tells us to calculate the total population for our case study

mobility_df.groupby("downtown_oakland").tot.sum()

downtown_oakland
0    4199461
1      14878
Name: tot, dtype: int64

In [63]:
#try calculating the average population for downtown oakland yourself.  How about the standard deviation?
mobility_df.groupby("downtown_oakland").tot.mean()

downtown_oakland
0   4671.26
1   2479.67
Name: tot, dtype: float64

In [64]:
#What about the total number of people who are inmigrants?
mobility_df.groupby("downtown_oakland").tot_inmigrant.sum()

downtown_oakland
0    250287
1      1837
Name: tot_inmigrant, dtype: int64

We can do a lot of the calculations using the built in calculations, but if we want to aggregate our MOEs, we need to use the square root sum of squares formula.  This is going to require a bit more work.

In the code below, I create a "dictionary" that assigns the "aggregation" functions I want to apply to each column. Sum is easy - I just want to "sum" the "tot" column.  For the MOE aggregation, I'm going to invoke a "lambda" function x, which is a more complicated mathematical operation.  

I'm going to assign a column function to get the "total" and "total_moe" for each variable I need to answer my reserach question.

In [65]:
#Here I am creating a "dictionary" that tells python what to do
aggregations = {"tot": "sum", "tot_moe" :lambda x: np.sqrt(np.sum(x)**2),
               "tot_samehouse": "sum", "tot_samehouse_moe" :lambda x: np.sqrt(np.sum(x)**2),
               "tot_inmigrant": "sum", "tot_inmigrant_moe": lambda x: np.sqrt(np.sum(x)**2)}
#Here I am creating a new case study dataframe, where I say "agg" the data using the "groupby" 
# dummy for "downtown_oakland", using the "aggregations" dictionary listed above
casestudy=mobility_df.groupby("downtown_oakland").agg(aggregations)
# Now just print my new dataframe so I can make sure it worked!
casestudy

,tot,tot_moe,tot_samehouse,tot_samehouse_moe,tot_inmigrant,tot_inmigrant_moe
downtown_oakland,,,,,,
0,4199461,329817,3646223,346503,250287,133772.09
1,14878,1166,11540,1358,1837,755.99

### 3.4 Calculating A Derived Proportion and MOE

Almost there!  Now, I'll calculate the percent that live in the same house, and the percent inmigrants, and the associated MOEs.  This code is starting to look familiar!

In [67]:
# This code calculates my variables of interest and their MOEs. 
# Notice how I have to call on the numpy library to do the square root.
# Also notice that I don't multiply by 100 to get a percentage - I want to leave it as a decimal to calculate my MOEs.
casestudy["pct_samehouse"]=casestudy["tot_samehouse"]/casestudy["tot"]
casestudy["pct_samehouse_moe"]=np.sqrt(casestudy['tot_samehouse_moe']**2 - 
                                          (casestudy['pct_samehouse']**2 * 
                                           casestudy['tot_moe']**2)) / casestudy['tot']

casestudy["pct_inmigrant"]=casestudy["tot_inmigrant"]/casestudy["tot"]
casestudy["pct_inmigrant_moe"]=np.sqrt(casestudy['tot_inmigrant_moe']**2 - 
                                          (casestudy['pct_inmigrant']**2 * 
                                           casestudy['tot_moe']**2)) / casestudy['tot']
casestudy[["pct_samehouse", "pct_samehouse_moe", "pct_inmigrant", "pct_inmigrant_moe"]]

,pct_samehouse,pct_samehouse_moe,pct_inmigrant,pct_inmigrant_moe
downtown_oakland,,,,
0,0.87,0.05,0.06,0.03
1,0.78,0.07,0.12,0.05

### 3.4 OPTIONAL: Testing for Statistical Signficance

Let's say I want to test to see if the difference between my downtown oakland case study community (downtown_oakland=1) is different from the rest of the Bay Area (downtown_oakland=0).  In practice, we wouldn't do this - we would get Alameda county or the Oakland City estimates. But to keep things simple to start, how might you enter the code below?

In [70]:
Z_CRIT=1.645
x1 = .87
x2 = .78

se_x1 = .05/Z_CRIT
se_x2 = .07/Z_CRIT

z=(x1 - x2)/np.sqrt(se_x1**2 + se_x2**2)
z

1.7210462916022438

Significant!!!  What about for in-migrants?

You now actually have all the code and tools you need to compare case study to Alameda county - try it over the weekend, and/or try this worksheet putting in your own data.  The goal is to just keep practicing writing code and making errors, so you get more familiar.  Just like learning a language, it feels unfamiliar at first and you'll make a lot of mistakes!